Bi3Smart-master/chat/urls.py
from django.urls import path, include
from chat.views import ThreadView

urlpatterns = [
    path('', ThreadView.as_view(),name='chat'),
    path('<str:username>/', ThreadView.as_view(),name='chat')
]

Bi3Smart-master/shoppingbd/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('store.urls')),
    path('cart/', include('carts.urls')),
    path('accounts/', include('accounts.urls')),
    path('order/', include('orders.urls')),
    path('chat/', include('chat.urls')),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

admin.site.site_header = "SHOPPING BD"
admin.site.site_title = "Controll Panel"
#admin.site.index_title = "IndexTitle"
#admin.site.site_url = "Url for view site button"

Bi3Smart-master/store/urls.py
from django.urls import path,include
from . import views

urlpatterns = [
    path('', views.store,name='store'),
    path('store/<slug:category_slug>/', views.store,name='product_by_category'),
    path('store/<slug:category_slug>/<slug:subcategory_slug>/', views.store,name='product_by_subcategory'),
    path('store/<slug:category_slug>/<slug:subcategory_slug>/<str:product_id>/', views.product_detail, name='product_detail'),
    path('search/',views.search,name='search'),
    path('submit_review/<int:product_id>/', views.submit_review, name='submit_review'),

]

Bi3Smart-master/store/models.py
from django.db import models
from ckeditor.fields import RichTextField
from category.models import Category,SubCategory
from django.utils.safestring import mark_safe
from django.urls import reverse
from accounts.models import Account
from django.db.models import Avg, Count
import math
# Create your models here.

class Product(models.Model):
    product_name=models.CharField(max_length=200)
    slug=models.SlugField(max_length=200)
    description=RichTextField(blank=True)
    price=models.IntegerField()
    image=models.ImageField(upload_to='photos/products')
    stock=models.IntegerField()
    is_available=models.BooleanField(default=True)
    category=models.ForeignKey(Category,on_delete=models.CASCADE)
    subcategory = models.ForeignKey(SubCategory, on_delete=models.CASCADE)
    created_date=models.DateTimeField(auto_now_add=True)
    modified_date=models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('-created_date', )

    def admin_photo(self):
        if self.image:
            return mark_safe('<img src="{}" width="100" />'.format(self.image.url))
        else:
            return mark_safe('<img src="{}" width="100" />'.format("/media/photos/thumbnail/empty.png"))
    admin_photo.short_description="Image"
    admin_photo.allow_tags=True



    def __str__(self):
        return self.product_name

    def get_url(self):
        return reverse('product_detail',args=[self.category.slug,self.subcategory.slug,self.id])

    def get_url2(self):
        return reverse('store',args=[self.category.slug,self.subcategory.slug])

    def averageReview(self):
        reviews = ReviewRating.objects.filter(product=self, status=True).aggregate(average=Avg('rating'))
        avg = 0
        if reviews['average'] is not None:
            avg = float(reviews['average'])
            whole = math.floor(avg)
            frac = avg - whole
            if (frac >= 0.5):
                all = whole + 0.5
                return  all
            else:
                return whole

        return avg

    def countReview(self):
        reviews = ReviewRating.objects.filter(product=self, status=True).aggregate(count=Count('id'))
        count = 0
        if reviews['count'] is not None:
            count = int(reviews['count'])
        return count



############### variation #######################

class VariationManager(models.Manager):
    def colors(self):
        return super(VariationManager, self).filter(variation_category='color', is_active=True)

    def sizes(self):
        return super(VariationManager, self).filter(variation_category='size', is_active=True)


class Variation(models.Model):

    VARIATION_CATEGORY = (
        ('color', 'color'),
        ('size', 'size'),
    )

    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    variation_category = models.CharField(max_length=100, choices=VARIATION_CATEGORY)
    variation_value = models.CharField(max_length=100)
    is_active = models.BooleanField(default=True)
    created_date = models.DateTimeField(auto_now_add=True)

    objects = VariationManager()

    def __str__(self):
        return self.variation_value


class ReviewRating(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    user = models.ForeignKey(Account, on_delete=models.CASCADE)
    subject = models.CharField(max_length=100, blank=True)
    review = models.TextField(max_length=500, blank=True)
    rating = models.FloatField()
    ip = models.CharField(max_length=20, blank=True)
    status = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.subject




# class ProductGallery(models.Model):
#     product = models.ForeignKey(Product, on_delete=models.CASCADE)
#     image = models.ImageField(upload_to='product/images/gallery/')
#
#     def __str__(self):
#         return self.product.product_name
#
#     class Meta:
#         verbose_name = 'productgallery'
#         verbose_name_plural = 'product gallery'

Bi3Smart-master/store/forms.py
from django import forms
from .models import ReviewRating


class ReviewForm(forms.ModelForm):
    class Meta:
        model = ReviewRating
        fields = ['subject', 'review', 'rating']

Bi3Smart-master/store/views.py
from django.shortcuts import render
from django.shortcuts import render,get_object_or_404, redirect
from .models import  Product,ReviewRating
from category.models import Category,SubCategory
from django.db.models import Count
from carts.views import _cart_id
from carts.models import CartItem
from django.core.paginator import EmptyPage,PageNotAnInteger,Paginator
from django.http import HttpResponse
from django.db.models import Q
from .forms import ReviewForm
from django.contrib import messages
from django.contrib.auth.decorators import login_required

def store(request,category_slug=None,subcategory_slug=None):
    products=None
    categories=None
    subcatagoriesname=None
    subcatagories=None

    if request.method=='post' or request.method=='POST':
        value=request.POST['materialExampleRadios']
        start=0
        end=0
        if int(value) == 1:
            start = 0
            end = 1000
        elif int(value)== 2:
            start = 1001
            end = 5000
        elif int(value) == 3:
            start = 5001
            end = 20000
        elif int(value) == 4:
            start = 20001
            end = 100000
        elif int(value) == 5:
            start = 100001
            end = 1000000

        if (category_slug != None) and (subcategory_slug == None):
            categories = get_object_or_404(Category, slug=category_slug)
            subcatagoriesname = SubCategory.objects.filter(category=categories).annotate(product_count=Count('product'))
            products = Product.objects.filter(category=categories, is_available=True,price__range=(start,end)).order_by('?')
            paginator = Paginator(products, 21)
            page = request.GET.get('page')
            products = paginator.get_page(page)

        elif subcategory_slug != None:
            subcatagories = get_object_or_404(SubCategory, slug=subcategory_slug)
            products = Product.objects.filter(subcategory=subcatagories, is_available=True ,price__range=(start,end)).order_by('?')
            categories = get_object_or_404(Category, slug=category_slug)
            subcatagoriesname = SubCategory.objects.filter(category=categories).annotate(product_count=Count('product'))
            paginator = Paginator(products, 21)
            page = request.GET.get('page')
            products = paginator.get_page(page)
        else:
            products = Product.objects.all().filter(is_available=True,price__range=(start,end)).order_by('?')
            paginator = Paginator(products, 21)
            page = request.GET.get('page')
            products = paginator.get_page(page)

        context = {
            'products': products,
            'subcatagoriesname': subcatagoriesname
        }
        return render(request, 'store/home.html', context)
##get
    if(category_slug != None) and (subcategory_slug==None):
        categories=get_object_or_404(Category,slug=category_slug)
        subcatagoriesname=SubCategory.objects.filter(category=categories).annotate(product_count=Count('product'))
        products = Product.objects.filter(category=categories,is_available=True).order_by('?')
        paginator=Paginator(products,21)
        page=request.GET.get('page')
        products=paginator.get_page(page)

    elif subcategory_slug!= None:
        subcatagories = get_object_or_404(SubCategory,slug=subcategory_slug)
        products = Product.objects.filter(subcategory=subcatagories,is_available=True).order_by('?')
        categories=get_object_or_404(Category,slug=category_slug)
        subcatagoriesname=SubCategory.objects.filter(category=categories).annotate(product_count=Count('product'))
        paginator=Paginator(products,21)
        page=request.GET.get('page')
        products=paginator.get_page(page)
    else:
        products=Product.objects.all().filter(is_available=True).order_by('?')
        paginator=Paginator(products,21)
        page=request.GET.get('page')
        products=paginator.get_page(page)

    context={
        'products':products,
        'subcatagoriesname':subcatagoriesname
    }
    return render(request,'store/home.html',context)




def product_detail(request,category_slug=None,subcategory_slug=None,product_id=None):
    try:
        single_product=Product.objects.get(category__slug=category_slug,subcategory__slug=subcategory_slug,id=product_id)
        in_cart=CartItem.objects.filter(cart__cart_id=_cart_id(request),product=single_product).exists()

    except Exception as e:
        raise e

    reviews = ReviewRating.objects.filter(product_id=single_product.id, status=True)

    context={
        'single_product':single_product,
        'in_cart':in_cart,
        'reviews': reviews,
    }

    return render(request, 'store/product_detail.html',context)


def search(request):
    products = None
    product_count=0

    if 'keyword' in request.GET:
        keyword=request.GET['keyword']
        if keyword:
            products=Product.objects.order_by('-created_date').filter(Q(product_name__icontains=keyword)) #| Q(description__icontains=keyword)
            product_count=products.count()
            paginator = Paginator(products, 21)
            page = request.GET.get('page')
            products = paginator.get_page(page)
    context={
        'products':products,
        'product_count':product_count

    }

    return render(request,'store/home.html',context)










@login_required(login_url='login')
def submit_review(request, product_id):
    url = request.META.get('HTTP_REFERER')
    if request.method == "POST":
        try:
            reviews = ReviewRating.objects.get(user__id=request.user.id, product__id=product_id)
            form = ReviewForm(request.POST, instance=reviews)
            form.save()
         #   messages.success(request, 'Thank you! Your review has been updated.')
            return redirect(url)
        except ReviewRating.DoesNotExist:
            form = ReviewForm(request.POST)
            if form.is_valid():
                data = ReviewRating()
                data.subject = form.cleaned_data['subject']
                data.review = form.cleaned_data['review']
                data.rating = form.cleaned_data['rating']
                data.ip = request.META.get('REMOTE_ADDR')
                data.product_id = product_id
                data.user_id = request.user.id
                data.save()
            #    messages.success(request, 'Thank you! Your review is live now.')
                return redirect(url)

Bi3Smart-master/templates/store/checkout.html
{% extends "base.html" %}
{% load static %}
{% block title %} Checkout {% endblock title %}





{% block content %}

<div class="container my-5" style="font-size: 1.5rem;">

<!--                      <form action="{% url 'place_order' %}" method="POST"  >-->
<form action="{% url 'place_order' %}" method="POST"  >

  <div class="row" >


<!-- cart start -->

    <h1 class="text-center mb-5 fw-bold" style="color: crimson">Checkout</h1>
    <div class="col-sm-8" style="border: 1px solid gray">
    <div class="card" >
     <div class="card-body mb-3 mt-5">

      <h1>Billing Address</h1>
<hr>
         <hr>

<!-- for loop end -->       {% csrf_token %}

                               <div class="row">
                                <div class="col form-group">
                                    <label >First Name</label>
                                        <input type="text" name="first_name" class="form-control" required>
                                </div>
                                <div class="col form-group">
                                    <label >Last Name</label>
                                    <input type="text" name="last_name" class="form-control" required>
                                </div>
                            </div>
                            <div class="row">

                                   <div class="col form-group">
                                    <label >Phone</label>
                                    <input type="tel" name="phone" class="form-control" required>
                                </div>
                                <div class="col form-group">
                                    <label >Email</label>
                                    <input type="email" name="email"  class="form-control" required>
                                </div>

                            </div>
                            <div class="row">
                                <div class="col form-group">
                                    <label >Address Line 1</label>
                                    <input type="text" name="address_line_1" class="form-control" required>
                                </div>
                                <div class="col form-group">
                                    <label >Address Line 2</label>
                                    <input type="tel" name="address_line_2" class="form-control" required>
                                </div>
                            </div>
                            <div class="row">

                               <div class="col form-group">
                                    <label >Pin Code</label>
                                    <input type="number" name="pin_code" class="form-control" required>
                                </div>
                                <div class="col form-group">
                                    <label >State</label>
                                    <input type="text" name="state" class="form-control" required>
                                </div>
                                <div class="col form-group">
                                    <label >City</label>
                                    <input type="text" name="city" class="form-control" required>
                                </div>

                            </div>
                            <div class="row">
                                <div class="col form-group">
                                    <label >Order Note</label>
                                    <textarea type="text" rows="2" name="order_note" class="form-control" required></textarea>
                                </div>
                            </div>



<!-- for loop end -->


     </div>
    </div>
  </div>
  <!-- cart end-->

  <!-- count start -->
  <div class="col-sm-4">
    <div class="card" >
     <div class="card-body mt-5 mb-5">

<!--      table start-->

   <table class="table table-borderless table-shopping-cart" style="font-size: 1.5rem;">
                            <thead class="text-muted">
                                <tr class="small text-uppercase">
                                    <th scope="col">Product</th>
                                    <th scope="col" width="120">Quantity</th>
                                    <th scope="col" width="120">Price</th>
                                </tr>
                            </thead>

                            <tbody>
                             {% for cart_item in cart_items %}

                                <tr>
                                    <td>
                                        <figure class="itemside align-items-center">
                                            <div class="aside"><img style="max-height: 5rem; max-width: 5rem;" src="{{ cart_item.product.image.url }}"
                                                    class="img-sm img-fluid"></div>
                                            <figcaption class="info">
                                                <a href="{{ cart_item.product.get_url }}"
                                                    class="title text-dark">{{ cart_item.product.product_name }}</a>
                                                <p class="text-muted small">

                                                    {% if cart_item.variations.all %}
                                                    {% for item in cart_item.variations.all %}
                                                    {{ item.variation_category | capfirst }} :
                                                    {{ item.variation_value | capfirst }} <br>
                                                    {% endfor %}
                                                    {% endif %}


                                                </p>
                                            </figcaption>
                                        </figure>
                                    </td>
                                    <td>
                                        <!-- col.// -->
                                        <label >{{cart_item.quantity}}</label>
                                    </td>
                                    <td>
                                        <div class="price-wrap">
                                            <var class="price">Dh {{ cart_item.sub_total }}</var> <br>
                                            <small class="text-muted"> Dh {{ cart_item.product.price }} each </small>
                                        </div> <!-- price-wrap .// -->
                                    </td>

                                </tr>

                           {% endfor %}

                            </tbody>
                        </table>
 <!--      table end-->



         <div class="d-grid"><a href="{% url 'store' %}" class="btn btn-danger mb-3" style="font-size: 1.3rem;">Continue Shopping</a></div>
       <div class="d-grid"><button type="submit"  value="Submit" class="btn btn-success" style="font-size: 1.3rem;">Place Order</button></div>



     </div>
    </div>
   </div>


  </div>
</form>
 </div>

   <!-- count end -->

 <!-- we accept part -->

 <div class="container">
  <div class="row">
   <div class="col-sm-8">
    <div class="card">
     <div class="card-body">
       <h5 class="mb-4 fw-bolder">We accept</h5>
       <img src="{% static 'images/payments.png' %}" alt="" class="img-fluid">
     </div>
   </div>
   </div>
  </div>
 </div>





{% endblock content%}

Bi3Smart-master/templates/store/product_detail.html
{% extends "base.html" %}
{% load static %}
{% block title %} Home {% endblock title %}





{% block content %}

<!-- product page -->
<div class="container mt-5" style="font-size: 2rem;">
  <div class="row gx-5">
    <div class="col-6">
      <img style="max-height: 50rem;"  src="{{single_product.image.url}}" alt="" class="img-fluid rounded">
    </div>
    <div class="col-1 "></div>

    <div class="col-md-5 ">
      <div class="mt-5 mt-md-0" >
<!--      form Start   -->
        <form action="{% url 'add_cart' single_product.id %}" method="POST">
      {% csrf_token %}
      <p class=" text-success">Store / {{single_product.category}} / {{single_product.subcategory}}</p>
      <h1 class="fw-bolder">{{single_product.product_name}}</h1>
      <h4 class="text-danger fw-bolder">Price: {{single_product.price}} DH</h4>

<!--          star start-->
                  <div class="rating-star">
                        <span>
                            <i class="{% if single_product.averageReview >= 1 %} fas fa-star   {% endif %}  " aria-hidden="true"></i>
                            <i class="{% if single_product.averageReview >= 2 %} fas fa-star   {% endif %}   " aria-hidden="true"></i>
                            <i class="{% if single_product.averageReview >= 3 %} fas fa-star   {% endif %}  " aria-hidden="true"></i>
                            <i class="{% if single_product.averageReview >= 4 %} fas fa-star  {% endif %}    " aria-hidden="true"></i>
                            <i class="{% if single_product.averageReview == 5 %} fas fa-star   {% endif %}   " aria-hidden="true"></i>

                             <i class="{% if single_product.averageReview == 0.5 %} fas fa-star-half  {% endif %}  " aria-hidden="true"></i>
                             <i class="{% if single_product.averageReview == 1.5 %} fas fa-star-half  {% endif %}  " aria-hidden="true"></i>
                             <i class="{% if single_product.averageReview == 2.5 %} fas fa-star-half  {% endif %}  " aria-hidden="true"></i>
                             <i class="{% if single_product.averageReview == 3.5 %} fas fa-star-half  {% endif %}  " aria-hidden="true"></i>
                             <i class="{% if single_product.averageReview == 4.5 %} fas fa-star-half  {% endif %}  " aria-hidden="true"></i>
                              <span  class="text-muted">{{single_product.countReview}} Reviews</span>
                        </span>
                    </div>
   <!--          star end-->

      <div>
        <p class="fw-bolder  "> Description: <span class="fw-normal text-muted">
          {{single_product.description|safe}}
              </span>
        </p>
      </div>

       {% if single_product.variation_set.colors %}
      <div class="mb-3">
        <p class="fw-bolder ">Choose Color</p>
      <select name="color" class="form-select form-control" aria-label="Default select example" required >
       <option value="" disabled selected>Select</option>
	    {% for i in single_product.variation_set.colors %}
	    <option value="{{ i.variation_value | lower }}">{{ i.variation_value | capfirst }}</option>
	    {% endfor %}
      </select>
      </div>

      <div class="mb-3">
        <p class="fw-bolder">Select Size</p>
      <select name="size" class="form-select form-control" aria-label="Default select example" required >
       <option value="" disabled selected>Select</option>
		{% for i in single_product.variation_set.sizes %}
		<option value="{{ i.variation_value | lower }}">{{ i.variation_value | capfirst }}</option>
		{% endfor %}
      </select>
      </div>
       {% endif %}

      <div class="mt-5">
        {% if single_product.stock <= 0 %}
        <h3 class="text-danger fw-bold">Out Of Stock</h3>
        {% else %}

        <button type="submit" class="btn btn-warning text-black" style="font-size: 1.3rem;">Add To Cart <i class="fa fa-shopping-cart"></i></button>

        {% endif %}
      </div>

     </form>        <!--      form end-->

    </div>
    </div>


  </div>
</div>


<!--another section-->

<!-- review start -->
<div class="container mt-5  " style="font-size: 1.5rem;">
  <br>
  <h1 class="text-danger fw-bolder text-center">Give Your Review</h1>
    <h2>Write your review</h2>
  <form action="{% url 'submit_review' single_product.id %}" method="POST">
      <label>How do you rate this product?</label>
      <br>

      <div class="rate">
        <input type="radio" name="rating" id="rating10" value="5" required /><label for="rating10" title="5"></label>
        <input type="radio" name="rating" id="rating9" value="4.5" required /><label for="rating9" title="4.5" class="half"></label>
        <input type="radio" name="rating" id="rating8" value="4" required /><label for="rating8" title="4"></label>
        <input type="radio" name="rating" id="rating7" value="3.5" required /><label for="rating7" title="3.5" class="half"></label>
        <input type="radio" name="rating" id="rating6" value="3" required /><label for="rating6" title="3"></label>
        <input type="radio" name="rating" id="rating5" value="2.5" required /><label for="rating5" title="2.5" class="half"></label>
        <input type="radio" name="rating" id="rating4" value="2" required /><label for="rating4" title="2"></label>
        <input type="radio" name="rating" id="rating3" value="1.5" required /><label for="rating3" title="1.5" class="half"></label>
        <input type="radio" name="rating" id="rating2" value="1" required /><label for="rating2" title="1"></label>
        <input type="radio" name="rating" id="rating1" value="0.5" required /><label for="rating1" title="0.5" class="half"></label>
    </div>

       {% csrf_token %}
    <div class="form-group">
      <label for="exampleInputEmail1" class="form-label">Review Title</label>
      <input type="text" class="form-control" id="exampleInputEmail1" name="subject" aria-describedby="emailHelp" required>
    </div>
    <div class="mb-3 form-group">
      <label for="exampleFormControlTextarea1" class="form-label">Review</label>
      <textarea class="form-control" id="exampleFormControlTextarea1" rows="3" name="review" required></textarea>
    </div>
 {% if user.is_authenticated %}
      <input type="submit" value="Submit Review" class="btn btn-primary p-3 " style="font-size:small">
      {% else %}
	<p>You must be logged in to post a review. </p>
			{% endif %}
  </form>
</div>
<!-- review end -->

<div class="container mt-5">
  <div>
  <h1 class="fw-bolder">Customer Reviews</h1>
 <!--          star start-->
<!--          <div>-->
<!--              <span class="fa fa-star checked"></span>-->
<!--              <span class="fa fa-star checked"></span>-->
<!--              <span class="fa fa-star checked"></span>-->
<!--              <span class="fa fa-star"></span>-->
<!--              <span class="fa fa-star"></span>-->
<!--          </div>-->
   <!--          star end-->

  <hr>
  </div>

{% for review in reviews %}
<!--  loop start-->
  <div class="mt-3">
  <div class="jumbotron jumbotron-fluid" >
    <div class="container">
       <div style="display: flex; justify-content: space-between;">
         <div>
         <h3 class="fw-bolder text-primary">{{ review.user.full_name }}</h3>
         <!--          star start-->
                    <div class="rating-star">
                        <span>
                            <i class="{% if review.rating >= 1 %} fas fa-star   {% endif %}  " aria-hidden="true"></i>
                            <i class="{% if review.rating >= 2 %} fas fa-star   {% endif %}   " aria-hidden="true"></i>
                            <i class="{% if review.rating >= 3 %} fas fa-star   {% endif %}  " aria-hidden="true"></i>
                            <i class="{% if review.rating >= 4 %} fas fa-star  {% endif %}    " aria-hidden="true"></i>
                            <i class="{% if review.rating == 5 %} fas fa-star   {% endif %}   " aria-hidden="true"></i>

                              <i class="{% if review.rating == 0.5 %} fas fa-star-half  {% endif %}  " aria-hidden="true"></i>
                             <i class="{% if review.rating == 1.5 %} fas fa-star-half  {% endif %}  " aria-hidden="true"></i>
                             <i class="{% if review.rating == 2.5 %} fas fa-star-half  {% endif %}  " aria-hidden="true"></i>
                             <i class="{% if review.rating == 3.5 %} fas fa-star-half  {% endif %}  " aria-hidden="true"></i>
                             <i class="{% if review.rating == 4.5 %} fas fa-star-half  {% endif %}  " aria-hidden="true"></i>

                        </span>
                    </div>
         <!--          star end-->

       </div>
       <div>{{ review.updated_at }}</div>
      </div>
      <div >
        <div>
        <h2>{{ review.subject }}</h2>
        <p style="font-size: 1.5rem">{{ review.review }}</p>
        <hr>
   </div>
   </div>
   </div>
  </div>
</div>
 {% endfor %}
  <!--  loop end-->



<!--//////////////////////////////////////////////////-->
</div>

{% endblock content%}